"""Authoritative mathematical tasks and continuation schedule. Default refresh never runs Lean."""

TASKS = [{'id': 'V01',
  'title': '原仓库：命题与证明审读',
  'group': '既有成果',
  'deps': [],
  'result': '已核对原项目的合法表达式、实际展开和字典序；良序结论限于 Desc(s) 与生成集 G。',
  'inputs': '原克隆提交 6533b2975f3cafb3582dc8f8127e9ea7144d7e69；宿主 Lean 证明。',
  'files': [],
  'accept': ['原项目独立检查和 210 项声明审计已有记录。', '宿主证明的完成不计作对象 KPω 主定理完成。'],
  'risk': '这是已有审读记录；当前看板没有重新编译原项目。',
  'evidence': ['../../verification-1y/REVIEW.zh-CN.md',
               '../../verification-1y/verification-status.json',
               '../../verification-1y/StatementAudit.lean'],
  'symbols': [],
  'declared_done': True,
  'critical': False,
  'size': 'M',
  'optional': False},
 {'id': 'F01',
  'title': 'KPω 公理、任意模型、Hilbert 桥',
  'group': '既有成果',
  'deps': [],
  'result': '纯 ∈ 理论包含完整集合归纳；从任意 KP 模型语义经完备性取得实际 Derives。',
  'inputs': 'YesMetaZFC 的一阶语法、Hilbert 核与完备性。',
  'files': [],
  'accept': ['对象理论没有加入 AC、幂集、完整分离或替换。', '不假设宿主 WellFounded mem 或模型 ω 标准。'],
  'risk': '',
  'evidence': ['Axioms', 'Model'],
  'symbols': [],
  'declared_done': True,
  'critical': False,
  'size': 'M',
  'optional': False},
 {'id': 'F02',
  'title': '集合、内部算术与递归基础',
  'group': '既有成果',
  'deps': ['F01'],
  'result': '集合函数、有限序列、Σ₁ 收集、Δ₁ 分离及有界/Σ₁ 递归的存在唯一性。',
  'inputs': '所有变量长度均为对象模型中的 n∈ω。',
  'files': [],
  'accept': ['递归产物是实际集合图，含所有前缀的总性和唯一性。'],
  'risk': '',
  'evidence': ['NaturalInduction', 'FunctionGraphs', 'SequenceSpaces', 'SigmaRecursion', 'DeltaOneSeparation'],
  'symbols': [],
  'declared_done': True,
  'critical': False,
  'size': 'M',
  'optional': False},
 {'id': 'F03',
  'title': '满意度、统一编译、初等性接口',
  'group': '既有成果',
  'deps': ['F02'],
  'result': '实际有限程序的满意度集合、内部任意长度合取/量词块编译与程序初等性。',
  'inputs': '同一程序代码在大小解释中求值。',
  'files': [],
  'accept': ['有编译正确性、变量作用域和实际满意度的联系。'],
  'risk': '',
  'evidence': ['SatisfactionTruth', 'UniformFiniteTemplates', 'ProgramElementarity', 'TarskiVaught'],
  'symbols': [],
  'declared_done': True,
  'critical': False,
  'size': 'M',
  'optional': False},
 {'id': 'F04',
  'title': '构造内模型 L 与 KPω + V=L',
  'group': '既有成果',
  'deps': ['F02', 'F03'],
  'result': '完整 L 层级、类内模型的 KPω（含收集及完整归纳）、相同 ω 与序数、内部 V=L。',
  'inputs': '使用对象归纳和集合证书。',
  'files': [],
  'accept': ['内模型不是额外假设；存在性与相应公理逐项导出。'],
  'risk': '',
  'evidence': ['ConstructibleKP', 'ConstructibleVL', 'ConstructibleOrdinalContent', 'CanonicalSyntaxInside'],
  'symbols': ['KP1Y.Constructible.inner_models_kp_d', 'KP1Y.Constructible.inner_v_equals_l_d'],
  'declared_done': True,
  'critical': False,
  'size': 'M',
  'optional': False},
 {'id': 'F05',
  'title': '构造良序、内部 κ≤ν 与统一 e',
  'group': '既有成果',
  'deps': ['F04'],
  'result': '从外部不可数 ν 得到 L 内最小不可数 κ≤ν，以及统一可数枚举 e。',
  'inputs': '实际构造良序、最小选择及函数图。',
  'files': [],
  'accept': ['选择的图由弱理论可用的集合构造得到。', '不要求 κ 在外部仍不可数。'],
  'risk': '',
  'evidence': ['ConstructibleWellorder', 'ConstructibleEnumeration', 'InnerEnumeration'],
  'symbols': ['KP1Y.Constructible.inner_least_uncountable_enumeration_d'],
  'declared_done': True,
  'critical': False,
  'size': 'M',
  'optional': False},
 {'id': 'F06',
  'title': 'R/FR 表、局部性、方程 (5)',
  'group': '既有成果',
  'deps': ['F02'],
  'result': '按 (b,K,θ) 序数阶段递归构造实际 R 表；证明严格端点、反射和根弱化。',
  'inputs': 'Reflection.Data、Table、Diagram、Template、Representation、Demand、Response。',
  'files': [],
  'accept': ['具体递归行的 Local 已证明；不是把局部性当输入。', '内部图边允许任意层 k；只有端点模板受 Adm 约束。'],
  'risk': '',
  'evidence': ['ReflectionTable', 'ReflectionSemantics', 'ReflectionLabelDomain'],
  'symbols': ['KP1Y.Reflection.table_exists_d', 'KP1Y.Reflection.Table.paper_equation_d'],
  'declared_done': True,
  'critical': False,
  'size': 'M',
  'optional': False},
 {'id': 'F07',
  'title': '具体结构与初等高度',
  'group': '既有成果',
  'deps': ['F03', 'F05', 'F06'],
  'result': '实际构造 A=(κ;<,R,P,e,ω) 的关系化结构和初等高度 δ。',
  'inputs': 'ArticleData、ArticleStructure.Valid、Height。',
  'files': [],
  'accept': ['δ<κ，ω、γ<δ；六个关系的含义逐项对应文稿。', '限制载域到 δ 时 top 仍为原 κ。'],
  'risk': '',
  'evidence': ['ReflectionStructure', 'ReflectionModelHeight', 'ReflectionAtomicBridge'],
  'symbols': [],
  'declared_done': True,
  'critical': False,
  'size': 'M',
  'optional': False},
 {'id': 'F08',
  'title': '变量族、图形索引与参数赋值',
  'group': '既有成果',
  'deps': ['F07'],
  'result': '内部任意宽度的无碰撞变量名；层参数、标量及输入/输出变量族的实际赋值。',
  'inputs': 'TemplateShape、NameFrame.Valid、GroundParameters。',
  'files': [],
  'accept': ['通过内部集合函数和同步覆盖构造，未用宿主有限次选择替代内部有限长度。'],
  'risk': '',
  'evidence': ['ReflectionTemplateShape', 'ReflectionNameFrame', 'ReflectionGroundParameters', 'AssignmentFamilyPatch'],
  'symbols': ['KP1Y.ReflectionModel.name_frame_exists_d', 'KP1Y.ReflectionModel.ground_parameters_exists_d'],
  'declared_done': True,
  'critical': False,
  'size': 'M',
  'optional': False},
 {'id': 'F09',
  'title': '二元原子、基础块与前缀语义',
  'group': '既有成果',
  'deps': ['F08', 'F03'],
  'result': '等号/小于原子块；正标签、cut 等式、输出界、前缀一致及大小结构候选限制。',
  'inputs': 'UniformConjoinBlock、BasicBlocks、PrefixValues、frame_restrict_below_cut。',
  'files': [],
  'accept': ['基础块的对象语义已核验；完整 Demand/Response 由后续 C06 交付。'],
  'risk': '',
  'evidence': ['ReflectionBasicCompilation',
               'ReflectionBasicHeight',
               'ReflectionPrefixBlock',
               'ReflectionOutputRestriction',
               'UniformConjoinBlock'],
  'symbols': [],
  'declared_done': True,
  'critical': False,
  'size': 'M',
  'optional': False},
 {'id': 'F10',
  'title': '(7) 正向的归纳步与反例提取',
  'group': '既有成果',
  'deps': ['F06'],
  'result': '在 TopAgreementBefore 假设下证明 P→Rδ；从 ¬P 提取实际有限反例。',
  'inputs': 'ReflectionTopInduction 中现有接口。',
  'files': [],
  'accept': ['保留归纳假设的边界；不能把此项算作完整 (7)。'],
  'risk': '',
  'evidence': ['ReflectionTopInduction'],
  'symbols': ['KP1Y.Reflection.top_to_height_d', 'KP1Y.Reflection.Table.counterexample_d'],
  'declared_done': True,
  'critical': False,
  'size': 'M',
  'optional': False},
 {'id': 'C00',
  'title': '冻结并行接口与所有权',
  'group': '反射支线',
  'deps': ['F08', 'F09', 'F10'],
  'result': '已冻结现有反射编译接口、索引块和参数槽位，明确有限算法与通用秩的独立交接边界。',
  'inputs': '本看板给出拟定契约；实施前由协调者确认，避免同时改基础类型。',
  'files': ['tracker/CONTRACTS.md'],
  'accept': ['记录字段、参数编号、命名空间、预期 theorem 类型及允许 imports。', '确认下列任务的负责文件互不重叠。', '不因计划写好了就标记接口冻结通过。'],
  'risk': '反射接口已冻结；实际算法编码由独立 Y00 任务交付。',
  'evidence': ['./CONTRACTS.md'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'S',
  'optional': False},
 {'id': 'C01',
  'title': 'R/P 紧凑原子代码与求值',
  'group': '反射支线',
  'deps': ['C00', 'F07'],
  'result': '构造三元 P、四元 R 的代码，证明存在、唯一、作用域、大小解释中的精确语义。',
  'inputs': 'AtomCode、Height.evaluate_atom_d；固定元数可以用 Fin，图形宽度必须内部化。',
  'files': ['KP1Y/ReflectionRelationCode.lean', 'KP1Y/ReflectionRelationCodeTruth.lean'],
  'accept': ['P(k,η,a) 精确读取 R(k,η,a,κ)。', '代码参数是变量名；不能误把语义标签塞进变量代码。', '同一代码用于大小结构。'],
  'risk': '',
  'evidence': ['ReflectionRelationCode', 'ReflectionRelationCodeTruth'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'M',
  'optional': False},
 {'id': 'C02',
  'title': '相邻递增原子块',
  'group': '反射支线',
  'deps': ['C00', 'F09'],
  'result': '为 f/g 生成相邻 Less 原子块，证明合取恰好是严格递增。',
  'inputs': 'BinaryBlock、AdjacentIncreasing ↔ Increasing、内部后继索引。',
  'files': ['KP1Y/ReflectionIncreasingBlock.lean'],
  'accept': ['覆盖宽度 0/1 或明确消费 TemplateShape 的非空前提。', '用对象自然数归纳处理任意内部长度。'],
  'risk': '',
  'evidence': ['ReflectionIncreasingBlock'],
  'symbols': [],
  'declared_done': True,
  'critical': False,
  'size': 'M',
  'optional': False},
 {'id': 'C03',
  'title': '可容许性 Adm 原子块',
  'group': '反射支线',
  'deps': ['C00', 'F09'],
  'result': '按固定图形索引和 K 选择真/假/小于原子，准确编译 Adm。',
  'inputs': 'k<K，或 k=K 且 q<c 且 f(q)<θ；GroundParameters 中 θ 的槽位。',
  'files': ['KP1Y/ReflectionAdmissionBlock.lean'],
  'accept': ['k<K 对应真；同层合法根对应 Less；其余对应假。', '不向内部图边添加 k<K 限制。'],
  'risk': '',
  'evidence': ['ReflectionAdmissionBlock'],
  'symbols': [],
  'declared_done': True,
  'critical': False,
  'size': 'M',
  'optional': False},
 {'id': 'C04',
  'title': '内部图边的 R 原子块',
  'group': '反射支线',
  'deps': ['C01', 'F08'],
  'result': '逐条 EdgeEntry 生成 R(k,fq,fp,fj) 和输出 g 的对应块。',
  'inputs': 'EdgeEntry 存在唯一、列界、NameFrame、C01 四元代码。',
  'files': ['KP1Y/ReflectionEdgeBlocks.lean', 'KP1Y/ReflectionEdgeBlockTruth.lean'],
  'accept': ['任意内部 edgeLength 的实际代码图。', '大小结构 AllAtoms 与原 Representation 中图边条件等价。'],
  'risk': '',
  'evidence': ['ReflectionEdgeBlocks', 'ReflectionEdgeBlockTruth'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'M',
  'optional': False},
 {'id': 'C05',
  'title': '端点模板的 P/R 原子块',
  'group': '反射支线',
  'deps': ['C01', 'F08'],
  'result': '分别构造顶端 P(k,fq,fp)、输出 R(k,gq,gp,a) 与供 (8) 使用的 P(k,gq,gp)。',
  'inputs': 'NeedEntry、层参数、point 标量槽位、C01。',
  'files': ['KP1Y/ReflectionEndpointBlocks.lean', 'KP1Y/ReflectionEndpointBlockTruth.lean'],
  'accept': ['输出 End_a 用四元 R，不能误用 P。', '(8) 的存在公式另用 P，不能带 δ 常元。'],
  'risk': '',
  'evidence': ['ReflectionEndpointBlocks', 'ReflectionEndpointBlockTruth'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'M',
  'optional': False},
 {'id': 'C06',
  'title': '完整 Demand/Response 统一编译',
  'group': '反射支线',
  'deps': ['C02', 'C03', 'C04', 'C05', 'F09'],
  'result': '把基础、递增、图边、端点和前缀块组合成完整输入/输出公式。',
  'inputs': '统一合取扩展、参数赋值、输入/输出量词框架。',
  'files': ['KP1Y/ReflectionTemplateCompilation.lean',
            'KP1Y/ReflectionTemplateTruth.lean',
            'KP1Y/ReflectionLabelingBridge.lean',
            'KP1Y/ReflectionTemplateEnvironment.lean'],
  'accept': ['实际 CompiledExtension 与同一代码的大小解释正确性。', 'Demand 和 Response 的每一个合取项均有双向等价。', '保留所有内部变量与图形长度。'],
  'risk': '',
  'evidence': ['ReflectionTemplateCompilation',
               'ReflectionTemplateTruth',
               'ReflectionLabelingBridge',
               'ReflectionTemplateEnvironment'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'C07',
  'title': '反例公式、量词块与反射',
  'group': '反射支线',
  'deps': ['C06', 'F07'],
  'result': '构造 ∃f (Input(f) ∧ ¬∃g Output(f,g)) 并从 κ 反射到 δ。',
  'inputs': 'ProgramElementary.reflect_counterexample_d；frame_restrict_below_cut。',
  'files': ['KP1Y/ReflectionCounterexampleCompilation.lean', 'KP1Y/ReflectionCounterexampleTransfer.lean'],
  'accept': ['所有自由参数属于 δ。', '证明候选输出 <a<δ 时大小载域的候选集合与真值一致。', '由真实满意度反射得到反例，而非直接假设反射结论。'],
  'risk': '',
  'evidence': ['ReflectionCounterexampleCompilation', 'ReflectionCounterexampleTransfer'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'C08',
  'title': '完成 (7)：双向等价及双重归纳',
  'group': '反射支线',
  'deps': ['C07', 'F10', 'F06'],
  'result': '对内部 K，再对 θ 归纳，消除 TopAgreementBefore，得到 P(K,θ,a)↔R(K,θ,a,δ)。',
  'inputs': '已有正向归纳步 + C07 反例传输。',
  'files': ['KP1Y/ReflectionHeightAgreement.lean'],
  'accept': ['∀K∈ω、θ≤a<δ；处理 a≤ω 的无效查询。', '最终定理没有遗留归纳假设。'],
  'risk': '',
  'evidence': ['ReflectionHeightAgreement'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'C09',
  'title': '(8) 的纯前缀存在公式',
  'group': '反射支线',
  'deps': ['C02', 'C04', 'C05', 'F09'],
  'result': '构造 ∃g [Rep(A,g) ∧ g↾c=u ∧ 顶端 P 模板]，并证明统一编译语义。',
  'inputs': '仅保存 f↾c；其余输入槽用 0；输出族量化全部列。',
  'files': ['KP1Y/ReflectionPrefixExistence.lean'],
  'accept': ['公式不含 δ、θ=δ 参数，不固定 g(c)=δ。', '省略 cut 等式、输出<a 和 Adm 块；无用标量槽设 0。', '即使 c=0 也可赋值。'],
  'risk': '(8) 的参数合法性是单独审查点，不能直接复用 C07 的 a、θ 参数化公式。',
  'evidence': ['ReflectionPrefixExistence'],
  'symbols': [],
  'declared_done': True,
  'critical': False,
  'size': 'L',
  'optional': False},
 {'id': 'C10',
  'title': '完成 (8)：初等高度的顶端反射',
  'group': '反射支线',
  'deps': ['C09', 'C08'],
  'result': '由原 f 提供大结构存在见证，经初等性取得 g<δ，再用 (7) 改写端点。',
  'inputs': 'C09 公式、Height、完整 (7)。',
  'files': ['KP1Y/ReflectionHeightTop.lean'],
  'accept': ['对所有 θ≤δ 证明 P(K,θ,δ)，包含 θ=δ。', '获得原 FR 所需的实际 Response。'],
  'risk': '',
  'evidence': ['ReflectionHeightTop'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'M',
  'optional': False},
 {'id': 'C11',
  'title': '内部有限次选取初等高度',
  'group': '反射支线',
  'deps': ['C00', 'F07', 'F02'],
  'result': '构造递增初等高度序列的实际集合图及每一行的高度证书。',
  'inputs': 'height_exists_d、可定义的规范选择/最小高度、已有内部递归。',
  'files': ['KP1Y/ReflectionHeightIteration.lean'],
  'accept': ['任意模型内部 m∈ω 的迭代；不是在 Lean 中做 m 次选择。', '规范选择谓词可定义，集合收集/递归前提全部满足。'],
  'risk': '',
  'evidence': ['ReflectionHeightIteration'],
  'symbols': [],
  'declared_done': True,
  'critical': False,
  'size': 'L',
  'optional': False},
 {'id': 'C12',
  'title': '初始表示：推论 7',
  'group': '反射支线',
  'deps': ['C11', 'C10', 'C08'],
  'result': '给每个有限根图实际构造 κ 以下的 Representation。',
  'inputs': '递增高度序列与 R(K,θ,α,β)；接到 Reflection.Diagram。',
  'files': ['KP1Y/ReflectionInitialRepresentation.lean'],
  'accept': ['每个图边均由 (8) 和 (7) 验证。', '宽度 0 返回空表示；任意层号均覆盖。'],
  'risk': '',
  'evidence': ['ReflectionInitialRepresentation'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'M',
  'optional': False},
 {'id': 'Y00',
  'title': '有限组合迁移清单与编码契约',
  'group': '有限组合',
  'deps': ['V01', 'F01', 'F02'],
  'result': '已核对79条源码声明、45条实际调用边，冻结内部表达式/森林/复制编码契约，并据此细分有限组合任务。',
  'inputs': 'OneY/RootIndexed/ExpansionWellFounded.lean:54；ZeroY/Structural 与 BM4。',
  'files': ['tracker/FINITE-PORT-CONTRACT.md', 'tracker/finite-port-map.json'],
  'accept': ['区分有限算术引理与宿主良基性/0-Y 假设。', '确认引用覆盖带帧及非标准状态；记录所需精确统一性。', '列出翻译到任意 KP 模型后的 theorem 形状。'],
  'risk': '源码调用审查已确认有限复制下降主链不消费 WF(0-Y/BM4)；原导入闭包中的良基性出口是旁支。',
  'evidence': ['./FINITE-PORT-CONTRACT.md', './finite-port-map.json'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Y06',
  'title': '有限复制下降：引理 3',
  'group': '有限组合',
  'deps': ['Y04b', 'Y05b', 'F06'],
  'result': '原表达式有末标签 β 的表示时，非空展开有末标签 <β 的表示。',
  'inputs': 'Y04 复制不变量、Y05 规范重建、F06 的严格性/弱化/FR。',
  'files': ['KP1Y/OneYCopyDescent.lean'],
  'accept': ['精确消费现有 Reflection 表接口；没有复制引理公理。', '删除、无坏根、复制及非空结果的所有分支覆盖。', '结论量化任意内部 N∈ω。'],
  'risk': 'copy_descent无条件（OneYMainTheorem）。',
  'evidence': ['OneYCopyDescent', 'OneYMainTheorem'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Y08',
  'title': 'L 与外部之间的有限计算绝对性',
  'group': '有限组合',
  'deps': ['Y08a', 'Y02k', 'Y05b'],
  'result': '同一个表达式、山形、展开计算证书在 L 与外部给出相同值。',
  'inputs': '内外相同 ω、传递性与图/序列绝对性；Y01/Y05 的真实计算谓词。',
  'files': ['KP1Y/OneYRankStatement.lean',
            'KP1Y/OneYInnerAbsoluteness.lean',
            'KP1Y/OneYInnerAbsolutenessExpansion.lean'],
  'accept': ['内部存在性、证书向上绝对性与外部唯一性识别同一个实际展开。', '覆盖全部内部输入，非仅每个标准输入。'],
  'risk': '',
  'evidence': ['OneYRankStatement', 'OneYInnerAbsoluteness', 'OneYInnerAbsolutenessExpansion'],
  'symbols': [],
  'declared_done': True,
  'critical': False,
  'size': 'L',
  'optional': False},
 {'id': 'O01',
  'title': '通用对象定理：秩函数推出良基与终止',
  'group': '结论支线',
  'deps': ['F01', 'F02'],
  'result': '从实际集合秩函数的严格下降，证明任意非空子集有极小元、集合编码轨迹到达终点。',
  'inputs': '实际 ordinal、Graph 与可定义单步关系；具体 1-Y 作为稍后的实例。',
  'files': ['KP1Y/RankedDynamics.lean'],
  'accept': ['用值域最小序数；不要求 dependent choice。', '清楚保留秩函数与下降作为通用定理前提，不当作最终结论。'],
  'risk': '',
  'evidence': ['RankedDynamics'],
  'symbols': [],
  'declared_done': True,
  'critical': False,
  'size': 'L',
  'optional': False},
 {'id': 'O02',
  'title': '通用对象定理：后代比较与字典序良序',
  'group': '结论支线',
  'deps': ['C00', 'O01'],
  'result': '在前缀可达、展开单调、种子共同祖先等精确假设下，用秩归纳比较后代。',
  'inputs': 'C00 的通用 reachability 接口；之后由 Y07 实例化。',
  'files': ['KP1Y/RankedDescendantOrder.lean'],
  'accept': ['Desc(s) 含自身，G 为种子后代并集。', '只对 Desc(s)/G 建立字典序与严格可达对应。', '不推出全体合法表达式 E 的字典序良序。'],
  'risk': '',
  'evidence': ['RankedDescendantOrder'],
  'symbols': [],
  'declared_done': True,
  'critical': False,
  'size': 'L',
  'optional': False},
 {'id': 'M01',
  'title': '最小末标签与实际 μ 图',
  'group': '主定理汇合',
  'deps': ['M01a', 'Y02k'],
  'result': '在内部 V=L 下，由表示末标签集合的最小元构造 μ:E→κ，空表达式取 0。',
  'inputs': '根图最小值接口 + 实际 E→A(s)；不等待坏根、复制或展开。',
  'files': ['KP1Y/OneYMinimumRank.lean'],
  'accept': ['是实际集合函数，非仅每个 s 存在某个秩。', '每个非空 s 有实现 μ(s) 的表示，且 μ(s)>0。'],
  'risk': '',
  'evidence': ['OneYMinimumRank'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'L',
  'optional': False,
  'delivered': False},
 {'id': 'M02',
  'title': 'μ 对所有实际展开严格下降',
  'group': '主定理汇合',
  'deps': ['M01', 'Y06'],
  'result': '用有限复制下降和最小化证明 μ(E_N(s))<μ(s)。',
  'inputs': '非空输出用 Y06；空输出用 μ(s)>0。',
  'files': ['KP1Y/OneYRankDescentStatement.lean', 'KP1Y/OneYRankDescent.lean'],
  'accept': ['∀非空 s∈E，∀N∈ω；所有展开分支覆盖。', '没有新增语义反射或初始表示前提。'],
  'risk': '经copy_descent无条件。',
  'evidence': ['OneYRankDescentStatement', 'OneYRankDescent'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'M',
  'optional': False},
 {'id': 'M03',
  'title': '回传实际 μ，去掉 V=L',
  'group': '主定理汇合',
  'deps': ['M02', 'Y08', 'F04', 'F05'],
  'result': '把 L 中同一个秩函数作为外部集合见证，得到某序数 χ≤ν 上的下降秩。',
  'inputs': 'inner_least_uncountable_enumeration_d；Y08 的算法绝对性。',
  'files': ['KP1Y/OneYRankTransfer.lean'],
  'accept': ['外部 μ:E→χ，χ≤ν；μ 的载域与展开含义未改变。', '回传的是集合秩见证，不是 L 内没有降链的断言。'],
  'risk': '经copy_descent无条件。',
  'evidence': ['OneYRankTransfer'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'M04',
  'title': '实例化良基与轨迹终止',
  'group': '主定理汇合',
  'deps': ['M03', 'O01', 'Y07r'],
  'result': '把真实 μ 和实际展开/Reach 接到通用秩定理，得到内部单步良基与每条集合编码轨迹到空。',
  'inputs': '实际 μ、实际 EN、前缀/种子数值事实。',
  'files': ['KP1Y/OneYWellFounded.lean'],
  'accept': ['解除 O01 的实际秩及下降前提。', '不额外使用选择或依赖选择。'],
  'risk': '',
  'evidence': ['OneYWellFounded'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'M',
  'optional': False},
 {'id': 'M05',
  'title': '封闭句子与实际 Hilbert Derives',
  'group': '主定理汇合',
  'deps': ['M04', 'M04b', 'F01'],
  'result': '将精确主定理和推论封装为纯 ∈ 闭句，经完备性得到 KP1Y.Derives。',
  'inputs': '最终模型定理对任意 M.Models KP1Y.theory；所有编码含义已核对。',
  'files': ['KP1Y/OneYTheoremData.lean',
            'KP1Y/OneYTheoremClauses.lean',
            'KP1Y/OneYTheoremSentence.lean',
            'KP1Y/OneYTheorem.lean',
            'KP1Y/OneYTheoremInputs.lean',
            'KP1Y/OneYMainAssembly.lean'],
  'accept': ['纯 ∈ 闭句为 ∀ν (UncountableOrdinal(ν) → ∃χ≤ν ∃μ …)。', '所有自由参数消除，无语义代理或额外假设。'],
  'risk': 'theorem1_derivable : KP1Y.Derives mainSentence，无前提；审计仅三项Lean元公理。',
  'evidence': ['OneYTheoremSentence',
               'OneYTheorem',
               'OneYMainAssembly',
               'OneYMainAssemblyCanonical',
               'OneYMainTheorem'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Q01',
  'title': '最终命题忠实性审读',
  'group': '最终验收',
  'deps': ['M05'],
  'result': '逐项对照 PDF 定理 1、原算法、纯 ∈ 句子及完整推导。',
  'inputs': '主定理展开打印、有限算法编码对应、引理依赖图。',
  'files': ['tracker/FINAL-STATEMENT-REVIEW.md'],
  'accept': ['检查 KP 公理表、内部 N、继承祖先、额外复制次数和 χ≤ν。', '检查空表达式、全部合法表达式的秩域、Desc/G 的良序域。', '条件接口全部由实际实现消除；不把源码文件名当作完成证据。'],
  'risk': 'Q01审读完成：无FINDING（LANE-E五路审读+LANE-A独立复核；kpsim.py对y1/engine.js差分223,952例0不符）。待Y05b接上后复核主定理无前提。',
  'evidence': ['./FINAL-STATEMENT-REVIEW.md', 'review/COPY-TOWER-FIDELITY.md'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'L',
  'optional': False,
  'delivered': True},
 {'id': 'Q02',
  'title': '最终增量集成、公理审计与复现',
  'group': '最终验收',
  'deps': ['Q01'],
  'result': '协调者统一根 imports、Audit.lean；检查实际依赖闭包并出具复现记录。',
  'inputs': '逐模块日志、严格阶段清单、源哈希、最终闭句审读。',
  'files': ['KP1Y.lean', 'Audit.lean', 'tracker/FINAL-VERIFICATION.md'],
  'accept': ['受影响模块增量检查全部通过，所选最终声明依赖无 sorryAx/新增公理。', '记录编译器、第三方来源和改动、当前完整快照。', '只有此关口通过才可报告完整证明完成。'],
  'risk': '',
  'evidence': ['./FINAL-VERIFICATION.md'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'M',
  'optional': False,
  'delivered': True},
 {'id': 'Z01',
  'title': '可选：落实n-row BMS的Z₂终止证明来源',
  'group': '可选调查',
  'deps': ['V01'],
  'result': '用户已澄清任意有限n-row BMS/0-Y(1,n)的Z₂终止结果；核对具体来源、n量词形状与可复用对象翻译。',
  'inputs': '2026-09-14用户补充；PTO(BMS)=PTO(Z₂)仅为猜想。',
  'files': ['tracker/Z2-REUSE-REVIEW.md'],
  'accept': ['区分每个固定行数与所有行数统一、强度比较与解释保持。', '若获得可复用对象推导，明确翻译与适用的带帧状态。', '没有来源时明确记录未知，主线继续迁移有限组合引理。'],
  'risk': '不由数学上界直接得到现成对象推导，不把逐n族与统一∀n互换；当前有限结构主线不依赖该良基性出口。',
  'evidence': ['./Z2-REUSE-REVIEW.md'],
  'symbols': [],
  'declared_done': False,
  'critical': False,
  'size': 'S',
  'optional': True},
 {'id': 'Y01a',
  'title': '实际表达式 E 与合法性',
  'group': '有限组合',
  'deps': ['Y00', 'F02'],
  'result': '实际 E、字面 Legal、长度唯一、空表达式、合法前缀/删除和 seeds。',
  'inputs': 'Y00 冻结契约；现有函数图、序列空间与自然数归纳。',
  'files': ['KP1Y/OneYExpression.lean'],
  'accept': ['实际 E、字面 Legal、长度唯一、空表达式、合法前缀/删除和 seeds。', '所有可变长度/数值在任意 KP 模型的内部ω；实际公式与集合图，稳定模块及审计通过。'],
  'risk': '具体源对应与接口见 FINITE-PORT-CONTRACT.md；不能以条件字段代替所需实际存在性。',
  'evidence': ['OneYExpression'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Y01b',
  'title': '内部算术与有界搜索基础',
  'group': '有限组合',
  'deps': ['Y01a'],
  'result': '后继/前驱、给定Δ0谓词的有界最右搜索、加法闭合及图、截断差的实际迭代。未声称已实现通用 Run 或全部乘除法。',
  'inputs': 'Y00 冻结契约；现有函数图、序列空间与自然数归纳。',
  'files': ['KP1Y/OneYFiniteComputation.lean'],
  'accept': ['后继/前驱、给定Δ0谓词的有界最右搜索、加法闭合及图、截断差的实际迭代。未声称已实现通用 Run 或全部乘除法。', '所有可变长度/数值在任意 KP 模型的内部ω；实际公式与集合图，稳定模块及审计通过。'],
  'risk': '具体源对应与接口见 FINITE-PORT-CONTRACT.md；不能以条件字段代替所需实际存在性。',
  'evidence': ['OneYFiniteComputation'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Y02a',
  'title': '父森林、路径、根、深度与选择',
  'group': '有限组合',
  'deps': ['Y01b'],
  'result': '实际部分父图、内部有限路径及长度界、根/深度存在唯一和实际图、最右继承选择、前缀局部性。',
  'inputs': '原 OneY.Build/Extraction/Forest 依赖；Y01 证书。',
  'files': ['KP1Y/OneYAncestry.lean',
            'KP1Y/OneYForestPaths.lean',
            'KP1Y/OneYForestSelection.lean',
            'KP1Y/OneYForestClosure.lean'],
  'accept': ['实际部分父图、内部有限路径及长度界、根/深度存在唯一和实际图、最右继承选择、前缀局部性。', '所有可变长度/数值在任意 KP 模型的内部ω；实际公式与集合图，稳定模块及审计通过。'],
  'risk': '具体源对应与接口见 FINITE-PORT-CONTRACT.md；不能以条件字段代替所需实际存在性。',
  'evidence': ['OneYAncestry', 'OneYForestPaths', 'OneYForestSelection', 'OneYForestClosure'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'XL',
  'optional': False},
 {'id': 'Y02b',
  'title': '数值山形与实际行运行',
  'group': '有限组合',
  'deps': ['Y02a', 'Y01c', 'Y02d'],
  'result': '实际 Forest 状态集合、差分与继承父选择、RowRun 的存在唯一。公开证书包装已追加，等待当前源码重新集成。',
  'inputs': '原 OneY.Build/Extraction/Forest 依赖；Y01 证书。',
  'files': ['KP1Y/OneYMountain.lean', 'KP1Y/OneYForestSpace.lean'],
  'accept': ['差分和继承父选择、实际行状态空间与行迭代、高度、伪父及提取。不得假设父图幂集存在。', '所有可变长度/数值在任意 KP 模型的内部ω；实际公式与集合图，稳定模块及审计通过。'],
  'risk': '具体源对应与接口见 FINITE-PORT-CONTRACT.md；不能以条件字段代替所需实际存在性。',
  'evidence': ['OneYMountain', 'OneYForestSpace'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'XL',
  'optional': False,
  'delivered': False},
 {'id': 'Y02c',
  'title': '有限层预算与全1尾界',
  'group': '有限组合',
  'deps': ['Y02g'],
  'result': '实际层/行预算和全1尾界；给规范图一个可定义、唯一的统一有限枚举界。',
  'inputs': '原 OneY.Build/Extraction/Forest 依赖；Y01 证书。',
  'files': ['KP1Y/OneYExtractionBounds.lean'],
  'accept': ['预算属于内部ω并由对象归纳证明。', '单独冻结预算出口，规范图不必等待坏根搜索完成。'],
  'risk': '具体源对应与接口见 FINITE-PORT-CONTRACT.md；不能以条件字段代替所需实际存在性。',
  'evidence': ['OneYExtractionBounds'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'XL',
  'optional': False,
  'delivered': False},
 {'id': 'Y03a',
  'title': '有限列运输与实际帧矩阵',
  'group': '有限组合',
  'deps': ['Y01b', 'Y02a', 'Y01c', 'Y02d'],
  'result': '严格列嵌入的父/祖先/根/深度双向运输，实际 cutoff 家族与有限帧矩阵，以及矩阵父图恢复。',
  'inputs': 'ZeroY/Structural、OneY/ForestFrameMatrix 与 TerminalFrame；Y00 依赖清单。',
  'files': ['KP1Y/OneYFrameTransport.lean', 'KP1Y/OneYFrameMatrix.lean'],
  'accept': ['严格列嵌入的父/祖先/根/深度双向运输，实际 cutoff 家族与有限帧矩阵，以及矩阵父图恢复。', '所有可变长度/数值在任意 KP 模型的内部ω；实际公式与集合图，稳定模块及审计通过。'],
  'risk': '通用帧矩阵及实际父运行恢复已完成；活动数值行与复制实例仍由Y03b/后续步骤处理。',
  'evidence': ['OneYFrameTransport', 'OneYFrameMatrix'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'XL',
  'optional': False},
 {'id': 'Y03b',
  'title': '完整矩阵展开、I/S保持与归一化',
  'group': '有限组合',
  'deps': ['Y03j', 'Y03f'],
  'result': '实际父复制全行族、完整DepthRegular/AboveS保持，以及空宽度/删除/复制/trim的实际算法总性唯一已完成。',
  'inputs': 'ZeroY/Structural、OneY/ForestFrameMatrix 与 TerminalFrame；Y00 依赖清单。',
  'files': ['KP1Y/OneYMatrixDepthExpansion.lean', 'KP1Y/OneYFiniteBlocker.lean', 'KP1Y/OneYMatrixNormalization.lean'],
  'accept': ['从实际父算法推导深度保持。', '根/非根及高/低行的 S 条件全部证明，无候选图等同的假设。'],
  'risk': '具体源对应与接口见 FINITE-PORT-CONTRACT.md；不能以条件字段代替所需实际存在性。',
  'evidence': ['OneYMatrixDepthExpansion', 'OneYFiniteBlocker', 'OneYMatrixNormalization'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'XL',
  'optional': False,
  'delivered': False},
 {'id': 'Y04a',
  'title': '唯一实际复制塔定义',
  'group': '有限组合',
  'deps': ['Y04o', 'Y04t', 'Y04l', 'Y04s', 'Y02n'],
  'result': '将已完成三种单层复制收成同一实际有限复制塔代码函数图，覆盖每个内部层号并证明整体唯一。',
  'inputs': '原 RootIndexed.ActualScheme 与 TerminalCopy 系列；抽象 R/FR 接口。',
  'files': ['KP1Y/OneYCopyTower.lean'],
  'accept': ['Y04/Y05 共同读取同一个复制定义。', '定义与图总性先冻结；后续几何保持另行证明。'],
  'risk': '具体源对应与接口见 FINITE-PORT-CONTRACT.md；不能以条件字段代替所需实际存在性。',
  'evidence': ['OneYCopyTower'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'XL',
  'optional': False,
  'delivered': False},
 {'id': 'Y04b',
  'title': '模板可容许性与反射拼接归纳',
  'group': '有限组合',
  'deps': ['Y04c', 'Y04d', 'F06'],
  'result': '精确 Adm、真实 FR 拼接、保留不变量及任意内部 N 次存在表示的对象归纳。',
  'inputs': '原 RootIndexed.ActualScheme 与 TerminalCopy 系列；抽象 R/FR 接口。',
  'files': ['KP1Y/OneYCopySeamsSplice.lean',
            'KP1Y/OneYCopySeamsStage.lean',
            'KP1Y/OneYCopySeamsStep.lean',
            'KP1Y/OneYCopySeamsSyntax.lean',
            'KP1Y/OneYCopySeamsInduction.lean'],
  'accept': ['精确 Adm 与单块 FR 拼接。', '对任意内部 N 的实际拼接图做对象归纳，得到严格递增表示。'],
  'risk': '具体源对应与接口见 FINITE-PORT-CONTRACT.md；不能以条件字段代替所需实际存在性。',
  'evidence': ['OneYCopySeamsSplice',
               'OneYCopySeamsStage',
               'OneYCopySeamsStep',
               'OneYCopySeamsSyntax',
               'OneYCopySeamsInduction'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'XL',
  'optional': False},
 {'id': 'Y05a',
  'title': '通用有限重建与燃料算法',
  'group': '有限组合',
  'deps': ['Y01d', 'Y02a'],
  'result': '给定真实有限父行/高度/顶部图，实际构造重建网格并证明唯一、三分支方程和不同界的前缀局部性；不假设NumericRow/Selects/RowRun。',
  'inputs': 'OneY.ExpansionCanonical、Reconstruction 与 Y01/Y02 编码。',
  'files': ['KP1Y/OneYReconstruction.lean', 'KP1Y/OneYReconstructionGrid.lean'],
  'accept': ['实际 valueFuel/重建函数图、唯一性、前缀局部性；输出值仍属于内部ω。', '所有可变长度/数值在任意 KP 模型的内部ω；实际公式与集合图，稳定模块及审计通过。'],
  'risk': '具体源对应与接口见 FINITE-PORT-CONTRACT.md；不能以条件字段代替所需实际存在性。',
  'evidence': ['OneYReconstruction', 'OneYReconstructionGrid'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'XL',
  'optional': False},
 {'id': 'Y05b',
  'title': '规范重新提取与根图对应',
  'group': '有限组合',
  'deps': ['Y05c', 'Y04z', 'Y04x', 'Y03k', 'Y02m', 'Y05n', 'Y05p', 'Y05o'],
  'result': '证明实际数值重建后重新提取恢复同一个复制塔，并识别 A(E_N(s)) 与所需图前缀。',
  'inputs': '实际CopyTower/Assembles、3种复制及根运输、图层装饰比较；数值恢复不依赖反射BlockScheme。原山形往返直接复用MountainReconstruction与ExpansionPrefix既有定理。',
  'files': ['KP1Y/OneYReconstructionCanonical.lean',
            'KP1Y/OneYReconstructionOrder.lean',
            'KP1Y/OneYReconstructionSelection.lean',
            'KP1Y/OneYTerminalCanonical.lean',
            'KP1Y/OneYTerminalTopBound.lean',
            'KP1Y/OneYReconstructionRecovery.lean',
            'KP1Y/OneYExpansionCanonical.lean',
            'KP1Y/OneYReconstructionExtraction.lean',
            'KP1Y/OneYTerminalExternal.lean',
            'KP1Y/OneYFrameCopy.lean',
            'KP1Y/OneYFrameCopyTransport.lean',
            'KP1Y/OneYLowerCanonical.lean',
            'KP1Y/OneYLowerTopBound.lean',
            'KP1Y/OneYLowerValueTransport.lean',
            'KP1Y/OneYLowerDepthTransport.lean',
            'KP1Y/OneYLowerPseudoTransport.lean',
            'KP1Y/OneYLowerUpperInputs.lean'],
  'accept': ['不用 NumericRow/Selects/RowRun 或规范性作为未解除输入。', '覆盖所有算法分支和内部长度；给出标准编码下原算法对应。'],
  'risk': 'canonical_copy_bound无条件（OneYMainTheorem）。',
  'evidence': ['OneYTowerCanonAssembly',
               'OneYTowerCanonLower',
               'OneYCanonicalExpansion',
               'OneYLowerLayerFinal',
               'OneYCanonHelperExits'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'XL',
  'optional': False},
 {'id': 'Y01c',
  'title': '共享全局减法表与序关系',
  'group': '有限组合',
  'deps': ['Y01b'],
  'result': '实际ω×ω→ω差表；差值界、正性iff b<a、严格下降、对角为0和相邻截断差的后继关系。',
  'inputs': '已冻结 TruncatedDifference；供 Mountain 与 Frame 共同使用，避免重复实现。',
  'files': ['KP1Y/OneYNaturalDifferenceFacts.lean', 'KP1Y/OneYNaturalDifferenceOrder.lean'],
  'accept': ['差表通过实际迭代器家族收集得到，差值性质通过对象自然数归纳证明。'],
  'risk': '',
  'evidence': ['OneYNaturalDifferenceFacts', 'OneYNaturalDifferenceOrder'],
  'symbols': [],
  'declared_done': True,
  'critical': False,
  'size': 'M',
  'optional': False},
 {'id': 'Y02d',
  'title': '共享线性森林与前缀祖先',
  'group': '有限组合',
  'deps': ['Y02a'],
  'result': '实际线性前驱父图及 Ancestor↔内部<，以及先前k列父图一致的局部版本。',
  'inputs': '供 Mountain 初始序列和 Frame cutoff 共用。',
  'files': ['KP1Y/OneYLinearForest.lean'],
  'accept': ['从内部路径定义证明双向对应，不引入宿主可达闭包。'],
  'risk': '',
  'evidence': ['OneYLinearForest'],
  'symbols': [],
  'declared_done': True,
  'critical': False,
  'size': 'M',
  'optional': False},
 {'id': 'Y01d',
  'title': '共享全局加乘表及代数律',
  'group': '有限组合',
  'deps': ['Y01b', 'Y01c'],
  'result': '实际全局加乘表、自然闭合、加乘交换/结合/分配与序性质，以及受界截断差的加法反解。',
  'inputs': '供矩阵复制地址、数值提升和通用重建共用；数据表与后续律分文件冻结。',
  'files': ['KP1Y/OneYNaturalAdditionTable.lean',
            'KP1Y/OneYNaturalAdditionFacts.lean',
            'KP1Y/OneYNaturalMultiplication.lean',
            'KP1Y/OneYNaturalMultiplicationLaws.lean',
            'KP1Y/OneYNaturalMultiplicationDistributivity.lean',
            'KP1Y/OneYNaturalDifferenceAddition.lean'],
  'accept': ['所有输入是模型内部ω；表是实际集合，律从明确对象schema归纳证明。'],
  'risk': '',
  'evidence': ['OneYNaturalAdditionTable',
               'OneYNaturalAdditionFacts',
               'OneYNaturalMultiplication',
               'OneYNaturalMultiplicationLaws',
               'OneYNaturalMultiplicationDistributivity',
               'OneYNaturalDifferenceAddition'],
  'symbols': [],
  'declared_done': True,
  'critical': False,
  'size': 'M',
  'optional': False},
 {'id': 'Y03c',
  'title': '实际有限矩阵展开核心',
  'group': '有限组合',
  'deps': ['Y03a', 'Y01d'],
  'result': '非退化上下文中，实际构造BM4矩阵展开、copy/local地址及ascending数值提升；覆盖、单射、全性与唯一性。',
  'inputs': '真实最大活动父行上下文；退化删除另用前缀接口。',
  'files': ['KP1Y/OneYMatrixExpansion.lean'],
  'accept': ['代码逐项对应原BM4公式；不把复制后父链或relative S当输入或已完成结论。'],
  'risk': '',
  'evidence': ['OneYMatrixExpansion'],
  'symbols': [],
  'declared_done': True,
  'critical': False,
  'size': 'M',
  'optional': False},
 {'id': 'Y04p',
  'title': '1-Y复制坐标的精确内部桥',
  'group': '有限组合',
  'deps': ['Y03c', 'Y02a'],
  'result': '按原copyIndex/copySource/move构造实际坐标图；核对(y,x]、source=x seam与首seam block=0。',
  'inputs': '复用通用地址覆盖/单射；显式区分1-Y的1-based source与BMS local。',
  'files': ['KP1Y/OneYCopyCoordinates.lean'],
  'accept': ['完整内部ω上的存在唯一和前缀/移动性质；不另造复制塔或全局算术。'],
  'risk': '',
  'evidence': ['OneYCopyCoordinates'],
  'symbols': [],
  'declared_done': True,
  'critical': False,
  'size': 'M',
  'optional': False,
  'delivered': False},
 {'id': 'Y02e',
  'title': '高度与顶部值的实际函数图',
  'group': '有限组合',
  'deps': ['Y02b'],
  'files': ['KP1Y/OneYMountainHeight.lean'],
  'result': '行燃料界、唯一 HeightGraph/TopValueGraph；活行与高度的等价保留原列为正的必要条件。',
  'inputs': '按前置任务的冻结接口交接；具体对象和未解除前提见验收。',
  'accept': ['给出内部行数界与高度/顶部图存在唯一。', '原列为0的边界单独处理，不能删除正性前提。'],
  'risk': '量化任意 KP 模型中的内部自然数；接口假设须由实际算法解除。',
  'evidence': ['OneYMountainHeight'],
  'symbols': [],
  'declared_done': True,
  'delivered': False,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Y02f',
  'title': '伪父选择与单次真实提取',
  'group': '有限组合',
  'deps': ['Y02e', 'Y02a'],
  'files': ['KP1Y/OneYMountainExtraction.lean'],
  'result': '按末行祖先及同/低一层高度选择最右伪父，再执行 Select，证明 RootedRow 保持及值下降。',
  'inputs': '按前置任务的冻结接口交接；具体对象和未解除前提见验收。',
  'accept': ['候选定义逐项对应原算法。', '单次提取实际存在唯一；大于1的值严格下降。'],
  'risk': '量化任意 KP 模型中的内部自然数；接口假设须由实际算法解除。',
  'evidence': ['OneYMountainExtraction'],
  'symbols': [],
  'declared_done': True,
  'delivered': False,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Y02g',
  'title': '提取证书与完整内部层运行',
  'group': '有限组合',
  'deps': ['Y02f', 'F02'],
  'files': ['KP1Y/OneYMountainLayerSyntax.lean', 'KP1Y/OneYMountainLayers.lean'],
  'result': '以一个实际 Σ₁ 见证打包行历史和高度图，收集提取步函数，构造完整 H:ω→层状态。',
  'inputs': '按前置任务的冻结接口交接；具体对象和未解除前提见验收。',
  'accept': ['Δ₀ 内部证书与 Σ₁ 无界打包明确区分。', 'LayerRun 逐层总性、真实 Extraction、唯一性及任意内部有限 trace。'],
  'risk': '量化任意 KP 模型中的内部自然数；接口假设须由实际算法解除。',
  'evidence': ['OneYMountainLayerSyntax', 'OneYMountainLayers'],
  'symbols': [],
  'declared_done': True,
  'delivered': False,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Y02n',
  'title': '坏根搜索与唯一性',
  'group': '有限组合',
  'deps': ['Y02c', 'Y02f'],
  'files': ['KP1Y/OneYBadRoot.lean'],
  'result': '准确表达有/无坏根分支、实际坏根搜索与唯一性，给出层号和行号界。',
  'inputs': '按前置任务的冻结接口交接；具体对象和未解除前提见验收。',
  'accept': ['搜索条件及最后列边界与原算法一致。', '存在条件明确；不假定每个非空表达式都存在坏根。'],
  'risk': '量化任意 KP 模型中的内部自然数；接口假设须由实际算法解除。',
  'evidence': ['OneYBadRoot'],
  'symbols': [],
  'declared_done': True,
  'delivered': False,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Y02j',
  'title': '内部有限过滤与稳定枚举',
  'group': '有限组合',
  'deps': ['Y01a', 'F02'],
  'files': ['KP1Y/OneYFiniteFilter.lean'],
  'result': '把有限部分单值图稳定压缩为实际列表与严格递增索引图；保留重复值。',
  'inputs': '按前置任务的冻结接口交接；具体对象和未解除前提见验收。',
  'accept': ['长度和索引均在内部ω，值域允许任意集合A。', '精确覆盖原定义域，存在唯一；不添加虚假填充原子。'],
  'risk': '量化任意 KP 模型中的内部自然数；接口假设须由实际算法解除。',
  'evidence': ['OneYFiniteFilter'],
  'symbols': [],
  'declared_done': True,
  'delivered': False,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Y02k',
  'title': '规范根图 A(s) 与实际全局图',
  'group': '有限组合',
  'deps': ['Y02c', 'Y02j', 'F06'],
  'files': ['KP1Y/OneYExpressionDiagram.lean', 'KP1Y/OneYExpressionDiagramGraph.lean'],
  'result': '按固定 (层,列,行) 顺序枚举全部真实父/根四元组，得到 ExprDiagram 及实际 E→A(s) 函数图。',
  'inputs': '按前置任务的冻结接口交接；具体对象和未解除前提见验收。',
  'accept': ['每一图边与原山形条件双向等价；行号不误作语义原子字段。', '含空表达式、孤立列、任意内部长度；证明 Reflection.Diagram。'],
  'risk': '量化任意 KP 模型中的内部自然数；接口假设须由实际算法解除。',
  'evidence': ['OneYExpressionDiagram', 'OneYExpressionDiagramGraph'],
  'symbols': [],
  'declared_done': True,
  'delivered': False,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Y02m',
  'title': '完整山形与规范图的前缀局部性',
  'group': '有限组合',
  'deps': ['Y02k'],
  'files': ['KP1Y/OneYMountainPrefix.lean'],
  'result': '把父图前缀相容提升到真实行运行、提取、层运行与规范图前缀。',
  'inputs': '按前置任务的冻结接口交接；具体对象和未解除前提见验收。',
  'accept': ['不能仅用森林前缀引理代替完整提取局部性。', '比较不同内部宽度和有限预算的输出。'],
  'risk': '量化任意 KP 模型中的内部自然数；接口假设须由实际算法解除。',
  'evidence': ['OneYMountainPrefix'],
  'symbols': [],
  'declared_done': True,
  'delivered': False,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Y03d',
  'title': '任意有限矩阵的真实父运行',
  'group': '有限组合',
  'deps': ['Y03c'],
  'files': ['KP1Y/OneYMatrixParents.lean'],
  'result': '为任意实际有限矩阵构造父算法的 MatrixParentRun。',
  'inputs': '按前置任务的冻结接口交接；具体对象和未解除前提见验收。',
  'accept': ['实际状态集合与内部迭代，无运行存在性的额外假设。'],
  'risk': '量化任意 KP 模型中的内部自然数；接口假设须由实际算法解除。',
  'evidence': ['OneYMatrixParents'],
  'symbols': [],
  'declared_done': True,
  'delivered': False,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Y03e',
  'title': '共同祖先链上的选择与深度比较',
  'group': '有限组合',
  'deps': ['Y02a'],
  'files': ['KP1Y/OneYSelectionOrder.lean',
            'KP1Y/OneYSelectionDepth.lean',
            'KP1Y/OneYDepthValues.lean',
            'KP1Y/OneYSelectionAncestorValues.lean',
            'KP1Y/OneYSelectionBlocker.lean'],
  'result': '选择父链的记录最小值比较、祖先/深度单调，以及根0/父边加1的值图等于真实深度。',
  'inputs': '按前置任务的冻结接口交接；具体对象和未解除前提见验收。',
  'accept': ['Selects false 的有序结论保留准确开关条件。', '内部集合归纳消除深度方程与路径深度之间的缺口。'],
  'risk': '量化任意 KP 模型中的内部自然数；接口假设须由实际算法解除。',
  'evidence': ['OneYSelectionOrder',
               'OneYSelectionDepth',
               'OneYDepthValues',
               'OneYSelectionAncestorValues',
               'OneYSelectionBlocker'],
  'symbols': [],
  'declared_done': True,
  'delivered': False,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Y03g',
  'title': '矩阵结构条件与列后缀次序',
  'group': '有限组合',
  'deps': ['Y03c'],
  'files': ['KP1Y/OneYMatrixStructuralDefs.lean'],
  'result': '冻结 DepthRegular、AboveS、RowBlocker 以及列后缀 Eq/Lt/Le 的精确定义。',
  'inputs': '按前置任务的冻结接口交接；具体对象和未解除前提见验收。',
  'accept': ['这里只是定义和基础序事实，不代表复制保持已证明。'],
  'risk': '量化任意 KP 模型中的内部自然数；接口假设须由实际算法解除。',
  'evidence': ['OneYMatrixStructuralDefs'],
  'symbols': [],
  'declared_done': True,
  'delivered': False,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Y03h',
  'title': '展开前缀与接缝数值事实',
  'group': '有限组合',
  'deps': ['Y03c', 'Y03d', 'Y03g'],
  'files': ['KP1Y/OneYMatrixExpansionFacts.lean'],
  'result': '实际展开的值/父/祖先前缀保持、增量正性及 ghost 接缝数值。',
  'inputs': '按前置任务的冻结接口交接；具体对象和未解除前提见验收。',
  'accept': ['逐分支绑定实际 MatrixExpansion，含精确行列界。'],
  'risk': '量化任意 KP 模型中的内部自然数；接口假设须由实际算法解除。',
  'evidence': ['OneYMatrixExpansionFacts'],
  'symbols': [],
  'declared_done': True,
  'delivered': False,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Y03i',
  'title': '局部父行嵌入与路径运输',
  'group': '有限组合',
  'deps': ['Y02a'],
  'files': ['KP1Y/OneYForestEmbedding.lean'],
  'result': '在映射像节点上对应父行，得到内部路径映射/逆像及祖先双向对应。',
  'inputs': '按前置任务的冻结接口交接；具体对象和未解除前提见验收。',
  'accept': ['目标允许其他复制块的节点和边，不能假设全图等于单个嵌入像。'],
  'risk': '量化任意 KP 模型中的内部自然数；接口假设须由实际算法解除。',
  'evidence': ['OneYForestEmbedding'],
  'symbols': [],
  'declared_done': True,
  'delivered': False,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Y03f',
  'title': '复制列提升保序与虚拟末列比较',
  'group': '有限组合',
  'deps': ['Y03e', 'Y03g', 'Y03h'],
  'files': ['KP1Y/OneYMatrixLiftOrder.lean', 'KP1Y/OneYMatrixGhostColumn.lean'],
  'result': '把共同父链与深度比较接到数值提升，证明同块后缀相等/严格小于/小于等于保持。',
  'inputs': '按前置任务的冻结接口交接；具体对象和未解除前提见验收。',
  'accept': ['Ascending 标志的单调由真实 Selects 导出。', '处理高度以外的补零行和虚拟末列；不预设提升保序。'],
  'risk': '量化任意 KP 模型中的内部自然数；接口假设须由实际算法解除。',
  'evidence': ['OneYMatrixLiftOrder', 'OneYMatrixGhostColumn'],
  'symbols': [],
  'declared_done': True,
  'delivered': False,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Y03j',
  'title': '复制父图与真实父算法相等',
  'group': '有限组合',
  'deps': ['Y03h', 'Y03i', 'Y03f', 'Y04p', 'Y03q', 'Y03s'],
  'files': ['KP1Y/OneYMatrixCopyLowSelection.lean', 'KP1Y/OneYMatrixCopyRun.lean'],
  'result': '以已构造的复制森林和数值加量公式，证明它恰等于展开矩阵重新计算的实际父运行。',
  'inputs': '按前置任务的冻结接口交接；具体对象和未解除前提见验收。',
  'accept': ['第0行线性候选森林、所有后继行继承候选与最右性。', '根/非根、高/低行、跨副本接缝全部覆盖。'],
  'risk': '量化任意 KP 模型中的内部自然数；接口假设须由实际算法解除。',
  'evidence': ['OneYMatrixCopyLowSelection', 'OneYMatrixCopyRun'],
  'symbols': [],
  'declared_done': True,
  'delivered': False,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Y03k',
  'title': '活动帧实例与装饰接缝比较',
  'group': '有限组合',
  'deps': ['Y03b', 'Y02f', 'Y03v'],
  'files': ['KP1Y/OneYActiveFrame.lean',
            'KP1Y/OneYSparseDepth.lean',
            'KP1Y/OneYActiveFrameTransport.lean',
            'KP1Y/OneYNumericDecoratedOrder.lean',
            'KP1Y/OneYForestDecoratedOrder.lean'],
  'result': '把数值山形接到活动帧矩阵，识别最大活动行及装饰列/接缝所需比较。',
  'inputs': '按前置任务的冻结接口交接；具体对象和未解除前提见验收。',
  'accept': ['对原重建真正消费的活动帧给出实例；不能只使用通用 Frame 接口。'],
  'risk': '量化任意 KP 模型中的内部自然数；接口假设须由实际算法解除。',
  'evidence': ['OneYActiveFrame',
               'OneYSparseDepth',
               'OneYActiveFrameTransport',
               'OneYNumericDecoratedOrder',
               'OneYForestDecoratedOrder'],
  'symbols': [],
  'declared_done': True,
  'delivered': False,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Y04c',
  'title': '复制的源事实与端点模板',
  'group': '有限组合',
  'deps': ['Y04a', 'Y02k', 'F06', 'Y04x'],
  'files': ['KP1Y/OneYAtomTransport.lean',
            'KP1Y/OneYCopyInvariant.lean',
            'KP1Y/OneYCopyIterationFacts.lean',
            'KP1Y/OneYCopyNeeds.lean',
            'KP1Y/OneYVirtualNeeds.lean',
            'KP1Y/OneYCopyNeedsSyntax.lean'],
  'result': '从源表示读取复制所需的源事实、根弱化和精确端点模板。',
  'inputs': '按前置任务的冻结接口交接；具体对象和未解除前提见验收。',
  'accept': ['模板层号、cut和旧根条件逐项对应文稿。', '精确k<K全height，k=K取r<level且r<height，K<k无项；按层/行稳定枚举并保留重复。', '不假设模板可容许或拼接表示已存在。'],
  'risk': 'CopyNeeds读取已复制塔的虚拟边界列width(b)，不是原末列边筛选。Lower边界height随b增长，需另行收集行界。所有量化仍覆盖内部ω。',
  'evidence': ['OneYAtomTransport',
               'OneYCopyInvariant',
               'OneYCopyIterationFacts',
               'OneYCopyNeeds',
               'OneYCopyNeedsSyntax',
               'OneYVirtualNeeds'],
  'symbols': [],
  'declared_done': True,
  'delivered': False,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Y04d',
  'title': '真实复制边分类与 BlockScheme',
  'group': '有限组合',
  'deps': ['Y04a', 'Y03k', 'Y02m', 'Y04x', 'Y04z'],
  'files': ['KP1Y/OneYCopyGeometry.lean', 'KP1Y/OneYCopySourceFacts.lean', 'KP1Y/OneYCopySpliceGeometry.lean'],
  'result': '证明真实复制塔的旧边、复制边和接缝边穷尽分类，并得到几何 BlockScheme。',
  'inputs': '按前置任务的冻结接口交接；具体对象和未解除前提见验收。',
  'accept': ['每一种实际边都有正确源边/接缝来源，反方向不多造边。'],
  'risk': '量化任意 KP 模型中的内部自然数；接口假设须由实际算法解除。',
  'evidence': ['OneYCopyGeometry', 'OneYCopySourceFacts', 'OneYCopySpliceGeometry'],
  'symbols': [],
  'declared_done': True,
  'delivered': False,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Y05c',
  'title': '实际 E_N 函数图与所有算法分支',
  'group': '有限组合',
  'deps': ['Y04a', 'Y05r', 'Y01a', 'Y05s'],
  'files': ['KP1Y/OneYExpansionCore.lean', 'KP1Y/OneYExpansionPrefix.lean', 'KP1Y/OneYExpansion.lean'],
  'result': '由唯一复制塔与通用数值重建得到实际 E×ω→E 的展开图，包含删除/无坏根/复制分支。',
  'inputs': '按前置任务的冻结接口交接；具体对象和未解除前提见验收。',
  'accept': ['证明实际总性、唯一性及合法性。', '空输入固定，N=0 删除末项，N 是额外复制次数。'],
  'risk': '原sequenceBound=max 1(maxValue s)，图用max+1严格界。实际EN需明确取非空严格界的前驱，或证明额外height0层的重建恒等性；不可直接把两个预算认相同。',
  'evidence': ['OneYExpansionCore', 'OneYExpansionPrefix', 'OneYExpansion'],
  'symbols': ['KP1Y.OneYFinite.Expansion.expansion_graph_exists_d',
              'KP1Y.OneYFinite.Expansion.Graph.zero_iff_drop_d',
              'KP1Y.OneYFinite.Expansion.Horizon.original_sequence_bound_d'],
  'declared_done': True,
  'delivered': False,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Y07r',
  'title': '实际有限 Reach 集合与首步分解',
  'group': '有限组合',
  'deps': ['Y05c', 'F02'],
  'files': ['KP1Y/OneYReachability.lean'],
  'result': '用内部有限展开路径构造 Reach 集合，证明拼接、反身传递和首步分解。',
  'inputs': '按前置任务的冻结接口交接；具体对象和未解除前提见验收。',
  'accept': ['实际集合与对象路径，不能采用宿主传递闭包代替。', '对接 O02 的精确 Reach 字段。'],
  'risk': '量化任意 KP 模型中的内部自然数；接口假设须由实际算法解除。',
  'evidence': ['OneYReachability'],
  'symbols': ['KP1Y.OneYFinite.Reachability.expansion_reachability_exists_d',
              'KP1Y.OneYFinite.Reachability.Relation.first_step_d'],
  'declared_done': True,
  'delivered': False,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Y07l',
  'title': '实际 Lex 集合与前缀次序',
  'group': '有限组合',
  'deps': ['Y01a', 'F02'],
  'files': ['KP1Y/OneYLexOrder.lean'],
  'result': '构造内部有限表达式上的严格字典序关系及前缀关系，证明所需基本序律。',
  'inputs': '按前置任务的冻结接口交接；具体对象和未解除前提见验收。',
  'accept': ['真前缀更小；实际关系图、传递性和不可反身性。'],
  'risk': '量化任意 KP 模型中的内部自然数；接口假设须由实际算法解除。',
  'evidence': ['OneYLexOrder'],
  'symbols': [],
  'declared_done': True,
  'delivered': False,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Y07a',
  'title': '实际展开的字典序与前缀事实',
  'group': '有限组合',
  'deps': ['Y05b', 'Y07r', 'Y07l'],
  'files': ['KP1Y/OneYExpansionOrder.lean',
            'KP1Y/OneYExpansionOrderColumn.lean',
            'KP1Y/OneYExpansionOrderLayer.lean',
            'KP1Y/OneYExpansionOrderSeam.lean',
            'KP1Y/OneYExpansionOrderLex.lean'],
  'result': '实际展开字典序下降、复制参数前缀单调以及前缀可达。',
  'inputs': '按前置任务的冻结接口交接；具体对象和未解除前提见验收。',
  'accept': ['逐项绑定真实 E_N，满足 O02 的全部相应字段。'],
  'risk': '量化任意 KP 模型中的内部自然数；接口假设须由实际算法解除。',
  'evidence': ['OneYExpansionOrder',
               'OneYExpansionOrderColumn',
               'OneYExpansionOrderLayer',
               'OneYExpansionOrderSeam',
               'OneYExpansionOrderLex'],
  'symbols': [],
  'declared_done': True,
  'delivered': False,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Y07b',
  'title': '实际 Seeds 与共同种子祖先',
  'group': '有限组合',
  'deps': ['Y07a'],
  'files': ['KP1Y/OneYSeeds.lean'],
  'result': '构造 seeds (1,m), m≥2，证明单步种子恒等式以及 G 内元素的共同种子祖先。',
  'inputs': '按前置任务的冻结接口交接；具体对象和未解除前提见验收。',
  'accept': ['E₁(1,n+2)=(1,n+1) 的参数和边界准确。', 'G 是实际可达后代并集，不扩大为所有 E。'],
  'risk': '量化任意 KP 模型中的内部自然数；接口假设须由实际算法解除。',
  'evidence': ['OneYSeeds'],
  'symbols': [],
  'declared_done': True,
  'delivered': False,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Y08a',
  'title': 'L 内外的有限编码域一致',
  'group': '有限组合',
  'deps': ['Y01a', 'F04'],
  'files': ['KP1Y/OneYInnerFiniteCodes.lean'],
  'result': '证明全部内部有限自然序列/计算代码在 L 内闭合，表达式载域内外一致。',
  'inputs': '按前置任务的冻结接口交接；具体对象和未解除前提见验收。',
  'accept': ['相同ω不是充分证明；处理内部非标准长度。', '给定代码绝对性与代码实际在L中分开证明。'],
  'risk': '量化任意 KP 模型中的内部自然数；接口假设须由实际算法解除。',
  'evidence': ['OneYInnerFiniteCodes'],
  'symbols': [],
  'declared_done': True,
  'delivered': False,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'M01a',
  'title': '任意根图的最小末标签',
  'group': '主定理汇合',
  'deps': ['C12', 'F06'],
  'files': ['KP1Y/OneYDiagramMinimumRank.lean'],
  'result': '先对任意实际有限根图构造最小末标签及实现该最小值的表示。',
  'inputs': '按前置任务的冻结接口交接；具体对象和未解除前提见验收。',
  'accept': ['最小化在可用集合界内完成。', '不以宿主选择代替实际集合图。'],
  'risk': '量化任意 KP 模型中的内部自然数；接口假设须由实际算法解除。',
  'evidence': ['OneYDiagramMinimumRank'],
  'symbols': [],
  'declared_done': True,
  'delivered': False,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'M04b',
  'title': '实例化 Desc/G 字典序良序',
  'group': '主定理汇合',
  'deps': ['M03', 'O02', 'Y07a', 'Y07b'],
  'files': ['KP1Y/OneYWellOrdering.lean'],
  'result': '由实际秩、Reach、Lex 和 Seeds 实例完成 Desc(s) 与 G 字典序良序。',
  'inputs': '按前置任务的冻结接口交接；具体对象和未解除前提见验收。',
  'accept': ['O02 的全部条件字段由实际定理提供。', '结论域严格限于 Desc(s)/G。'],
  'risk': '量化任意 KP 模型中的内部自然数；接口假设须由实际算法解除。',
  'evidence': ['OneYWellOrdering'],
  'symbols': [],
  'declared_done': True,
  'delivered': False,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Y03q',
  'title': '候选复制森林与完整祖先几何',
  'group': '有限组合',
  'deps': ['Y03h', 'Y03i', 'Y04p', 'Y03e'],
  'files': ['KP1Y/OneYMatrixCopyForest.lean'],
  'result': '实际分支复制父图、左向/唯一、保留前缀、同副本好/坏部祖先、前块接缝和所有祖先来源分解。',
  'inputs': '按前置任务的冻结接口交接；具体对象和未解除前提见验收。',
  'accept': ['候选图确实是实际森林，全部来源分解已证。', '此节点不含实际Selects识别或DepthRegular/S保持，后续Y03j负责。'],
  'risk': '量化任意 KP 模型中的内部自然数；接口假设须由实际算法解除。',
  'evidence': ['OneYMatrixCopyForest'],
  'symbols': [],
  'declared_done': True,
  'delivered': False,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Y03s',
  'title': '高行与坏部父项的真实选择识别',
  'group': '有限组合',
  'deps': ['Y03q', 'Y03f', 'Y03h'],
  'files': ['KP1Y/OneYMatrixCopySelection.lean'],
  'result': '复制线性初始森林、完整高行Selects父行iff、坏部父项的实际RestrictedParent及源候选界。',
  'inputs': '按前置任务的冻结接口交接；具体对象和未解除前提见验收。',
  'accept': ['已识别的高行/坏部范围有双向实际算法定理。', '低行好部、无父及root seam、完整行族仍由Y03j完成。'],
  'risk': '量化任意 KP 模型中的内部自然数；接口假设须由实际算法解除。',
  'evidence': ['OneYMatrixCopySelection'],
  'symbols': [],
  'declared_done': True,
  'delivered': False,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Y02p',
  'title': '提取/层祖先与实际低层根高度',
  'group': '有限组合',
  'deps': ['Y02g', 'Y02n', 'Y02a'],
  'result': '从真实伪父和提取导出行/层祖先向下运输，证明活动坏根在较低层的严格高度与精确组件根等式。',
  'inputs': '原 RootIndexed.ActualScheme 与 TerminalCopy 系列；抽象 R/FR 接口。',
  'files': ['KP1Y/OneYMountainRelations.lean', 'KP1Y/OneYActiveGeometry.lean'],
  'accept': ['各refines由实际算法推导，无TopForest/根等式的额外字段。', 'k<K时Height(y)<Height(x)，且row Height(y)中x的实际Root为y。'],
  'risk': '具体源对应与接口见 FINITE-PORT-CONTRACT.md；不能以条件字段代替所需实际存在性。',
  'evidence': ['OneYMountainRelations', 'OneYActiveGeometry'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'XL',
  'optional': False,
  'delivered': False},
 {'id': 'Y04o',
  'title': '普通复制坐标与实际共同山形',
  'group': '有限组合',
  'deps': ['Y04p', 'Y02g'],
  'result': '实际[root,last)普通解码、共同有限宽山形Data及FromRun、完整Ordinary复制与总性唯一。',
  'inputs': '原 RootIndexed.ActualScheme 与 TerminalCopy 系列；抽象 R/FR 接口。',
  'files': ['KP1Y/OneYOrdinaryCoordinates.lean', 'KP1Y/OneYCopiedMountain.lean', 'KP1Y/OneYOrdinaryCopy.lean'],
  'accept': ['区别普通source0/block0与raw的(root,last]约定。', '实际无限ω父行家族；不假设所有ω函数空间。'],
  'risk': '具体源对应与接口见 FINITE-PORT-CONTRACT.md；不能以条件字段代替所需实际存在性。',
  'evidence': ['OneYOrdinaryCoordinates', 'OneYCopiedMountain', 'OneYOrdinaryCopy'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'XL',
  'optional': False,
  'delivered': False},
 {'id': 'Y04t',
  'title': '活跃层Terminal复制',
  'group': '有限组合',
  'deps': ['Y04o', 'Y02n'],
  'result': '从真实BadAt构造活跃层复制，接缝高度取root；高行父边取原root且不平移。',
  'inputs': '原 RootIndexed.ActualScheme 与 TerminalCopy 系列；抽象 R/FR 接口。',
  'files': ['KP1Y/OneYTerminalCopy.lean'],
  'accept': ['实际height/parent图、完整Data.Valid、Copies唯一。', 'Active和lastHeight由真实坏根解除。'],
  'risk': '具体源对应与接口见 FINITE-PORT-CONTRACT.md；不能以条件字段代替所需实际存在性。',
  'evidence': ['OneYTerminalCopy'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'XL',
  'optional': False,
  'delivered': False},
 {'id': 'Y04r',
  'title': '低层复制的行移位算术',
  'group': '有限组合',
  'deps': ['Y01d'],
  'result': '真实ShiftedRow图与有界语法；固定floor/反解r−off，严格高度与端点界运输。',
  'inputs': '原 RootIndexed.ActualScheme 与 TerminalCopy 系列；抽象 R/FR 接口。',
  'files': ['KP1Y/OneYLowerRowShift.lean'],
  'accept': ['使用共享加减法表，所有输入是内部ω。'],
  'risk': '具体源对应与接口见 FINITE-PORT-CONTRACT.md；不能以条件字段代替所需实际存在性。',
  'evidence': ['OneYLowerRowShift'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'XL',
  'optional': False,
  'delivered': False},
 {'id': 'Y04l',
  'title': '低层Lower复制',
  'group': '有限组合',
  'deps': ['Y04o', 'Y02p', 'Y04r'],
  'result': '原段、锥内gap/高行纯平移和未移动ParentCopy的精确复制；完整数据图、几何和唯一性。',
  'inputs': '原 RootIndexed.ActualScheme 与 TerminalCopy 系列；抽象 R/FR 接口。',
  'files': ['KP1Y/OneYLowerCopy.lean'],
  'accept': ['从真实BadAt读取恢复完整Context，根/高度/coherence不作为额外假设。', '纯Encode与ParentCopy不能混用。'],
  'risk': '具体源对应与接口见 FINITE-PORT-CONTRACT.md；不能以条件字段代替所需实际存在性。',
  'evidence': ['OneYLowerCopy'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'XL',
  'optional': False,
  'delivered': False},
 {'id': 'Y04s',
  'title': '统一山形及三分支有界证书',
  'group': '有限组合',
  'deps': ['Y04o', 'Y04t', 'Y04l'],
  'result': 'Data.Valid/FromRun和三种Copies的字面Δ0/Closed/iff；代码自身有界读取height/parents。',
  'inputs': '原 RootIndexed.ActualScheme 与 TerminalCopy 系列；抽象 R/FR 接口。',
  'files': ['KP1Y/OneYCopiedMountainSyntax.lean', 'KP1Y/OneYCopyBranchSyntax.lean'],
  'accept': ['无界原述由实际图界等价化。', '不引入全部ω→Forests函数空间。'],
  'risk': '具体源对应与接口见 FINITE-PORT-CONTRACT.md；不能以条件字段代替所需实际存在性。',
  'evidence': ['OneYCopiedMountainSyntax', 'OneYCopyBranchSyntax'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'XL',
  'optional': False,
  'delivered': False},
 {'id': 'Y05r',
  'title': '实际单层与有限塔数值重建',
  'group': '有限组合',
  'deps': ['Y05a', 'Y04s'],
  'result': '从代码化山形实际构造有限Grid并读底行，再作内部倒序塔迭代；顶层全1，证明总性/唯一/合法性及FromRun恢复。',
  'inputs': '原 RootIndexed.ActualScheme 与 TerminalCopy 系列；抽象 R/FR 接口。',
  'files': ['KP1Y/OneYMountainReconstruction.lean', 'KP1Y/OneYTowerReconstruction.lean'],
  'accept': ['不得用宿主fold或点态存在代替内部实际迭代图。', '规范重提取仍由Y05b证明。'],
  'risk': '具体源对应与接口见 FINITE-PORT-CONTRACT.md；不能以条件字段代替所需实际存在性。',
  'evidence': ['OneYMountainReconstruction', 'OneYTowerReconstruction'],
  'symbols': [],
  'declared_done': True,
  'critical': True,
  'size': 'XL',
  'optional': False,
  'delivered': False},
 {'id': 'Y03v',
  'title': '复制Top图与装饰矩阵展开保持',
  'group': '有限组合',
  'deps': ['Y03b', 'Y03f', 'Y04o'],
  'files': ['KP1Y/OneYDecoratedMatrixExpansion.lean'],
  'result': '独立Top值的实际复制图，以及装饰RowS在完整矩阵展开中的保持；与源Numeric装饰证明分文件。',
  'inputs': '按前置任务的冻结接口交接；具体对象和未解除前提见验收。',
  'accept': ['严格后缀分支不添加Top比较前提。', '空/删除/复制/trim均绑定实际矩阵算法，复制Top由OrdinaryCoordinates构造。'],
  'risk': '量化任意 KP 模型中的内部自然数；接口假设须由实际算法解除。',
  'evidence': ['OneYDecoratedMatrixExpansion'],
  'symbols': ['KP1Y.OneYFinite.matrix_expansion_decorated_exists_d'],
  'declared_done': True,
  'delivered': False,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Y05s',
  'title': '复制塔的有界集合证书',
  'group': '有限组合',
  'deps': ['Y04a'],
  'files': ['KP1Y/OneYCopyTowerCertificates.lean'],
  'result': '由实际函数图、像覆盖和点计算的唯一性恢复完整SourceGraph/Tower，给出literal Δ0/Closed/iff。',
  'inputs': '已证LayerRun/RowFamily、实际BadAt、真实SourceGraph及森林空间。',
  'accept': ['两种证书均与已有实际对象规格双向等价。', '不引入全部ω函数空间或额外算法公理。'],
  'risk': '',
  'evidence': ['OneYCopyTowerCertificates'],
  'symbols': ['KP1Y.OneYFinite.CopyTower.sourceGraphCertificateFormula_iff',
              'KP1Y.OneYFinite.CopyTower.towerCertificateFormula_iff'],
  'declared_done': True,
  'delivered': False,
  'critical': True,
  'size': 'M',
  'optional': False},
 {'id': 'Y04x',
  'title': '复制根及源父记录的真实运输',
  'group': '有限组合',
  'deps': ['Y04a', 'Y02m', 'Y03k'],
  'files': ['KP1Y/OneYTerminalCopyRoots.lean',
            'KP1Y/OneYLowerCopyRoots.lean',
            'KP1Y/OneYCopyPathTransport.lean',
            'KP1Y/OneYOrdinaryCopyRoots.lean',
            'KP1Y/OneYTerminalCopyHighRoots.lean'],
  'result': '从真实复制父图导出Root/source分类；活跃层低seam根保持且严格小于控制根，Lower连接实际shifted源行。',
  'inputs': '真实源RowRun/FromRun/正性、实际BadAt或已构造Context.Valid、实际目标Copies。',
  'accept': ['不把CopiedRoot作为假设；路径/列归纳在对象ω中进行。',
             '虚拟边界列width(b)给出完整父与根源见证。',
             'Terminal/Lower由不同负责人独占，不重复CopyNeeds枚举或Virtual语义组合。'],
  'risk': 'Data.Valid的局部高度条件不能代替真实数值RowRun的祖先细化。',
  'evidence': ['OneYTerminalCopyRoots',
               'OneYCopyPathTransport',
               'OneYOrdinaryCopyRoots',
               'OneYLowerCopyRoots',
               'OneYTerminalCopyHighRoots'],
  'symbols': ['KP1Y.OneYFinite.CopiedMountain.Terminal.Copies.low_seam_source_d'],
  'declared_done': True,
  'delivered': False,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Y04z',
  'title': '复制塔的规范原子表及实际图',
  'group': '有限组合',
  'deps': ['Y04a', 'Y02j', 'F06'],
  'files': ['KP1Y/OneYCopyDiagramAtoms.lean', 'KP1Y/OneYCopyDiagram.lean'],
  'result': '按(层,列,行)稳定枚举实际复制塔全部父/根原子，构造真实edgeLists及Reflection.Diagram。',
  'inputs': 'CopyTower.Tower或实际有限代码塔Graph+CodeValid，逐层height界及统一有限行界。',
  'accept': ['每一EdgeAt与真实该层某行RootAt/ParentAt双向对应，保留重复。', '不预设目标Numeric/RowRun或规范重提取。', '仅使用已存在的内部有限图和合法收集，不能造全部ω函数空间。'],
  'risk': '与CopyNeeds的虚拟边界模板区分；不重复其NeedRow枚举。',
  'evidence': ['OneYCopyDiagramAtoms', 'OneYCopyDiagram'],
  'symbols': [],
  'declared_done': True,
  'delivered': False,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Y05n',
  'title': '三种复制的相邻父行精化',
  'deps': ['Y04a', 'Y04x', 'Y02m'],
  'files': ['KP1Y/OneYCopyNestingDefs.lean',
            'KP1Y/OneYCopyAncestryTransport.lean',
            'KP1Y/OneYOrdinaryCopyNesting.lean',
            'KP1Y/OneYTerminalCopyNesting.lean',
            'KP1Y/OneYLowerCopyNesting.lean',
            'KP1Y/OneYCopyNesting.lean',
            'KP1Y/OneYLowerRowShiftSuccessor.lean'],
  'result': '由真实源RowRun和三种实际Copies导出相邻父行ForestRefines，最终装配统一Nested。',
  'accept': ['所有行/列归纳在对象模型内部进行。', '不从Data.Valid默推Nested，不依赖Top或重建数值。'],
  'group': '有限组合',
  'inputs': '实际源RowRun/FromRun、冻结复制Data/Copies和内部有限编码。',
  'risk': '不能把尚待证明的选择、Nested或规范性作为最终Expands前提。',
  'evidence': ['OneYCopyNestingDefs',
               'OneYCopyAncestryTransport',
               'OneYOrdinaryCopyNesting',
               'OneYTerminalCopyNesting',
               'OneYLowerCopyNesting',
               'OneYCopyNesting',
               'OneYLowerRowShiftSuccessor'],
  'symbols': [],
  'declared_done': True,
  'delivered': True,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Y05p',
  'title': '图层伪父候选与实际父图',
  'deps': ['Y04a', 'F02'],
  'files': ['KP1Y/OneYGraphPseudoDefs.lean', 'KP1Y/OneYGraphPseudo.lean'],
  'result': '按真实height=succ r、F_r祖先和端点高度条件定义候选，以有限最大搜索构造真实伪父图。',
  'accept': ['候选存在由实际行根和高度证明；不附加Numeric或不必要的Nested。', '定义唯一，工厂与canonical选择准则共同复用。'],
  'group': '有限组合',
  'inputs': '实际源RowRun/FromRun、冻结复制Data/Copies和内部有限编码。',
  'risk': '不能把尚待证明的选择、Nested或规范性作为最终Expands前提。',
  'evidence': ['OneYGraphPseudoDefs', 'OneYGraphPseudo'],
  'symbols': [],
  'declared_done': True,
  'delivered': False,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Y05o',
  'title': '普通复制数值与重新提取',
  'deps': ['Y05r', 'Y04x', 'Y05n', 'Y02m'],
  'files': ['KP1Y/OneYOrdinaryForestTransport.lean',
            'KP1Y/OneYOrdinaryValueTransport.lean',
            'KP1Y/OneYOrdinaryPseudoTransport.lean',
            'KP1Y/OneYOrdinaryCanonical.lean'],
  'result': '证明实际普通复制重建值等于原source0行值，真实Selects运输及重新提取保持普通复制。',
  'accept': ['绑定实际Grid/Reconstructs及独立Top复制图。', '消除最近更小选择前提，供Terminal高行及上层塔消费。'],
  'group': '有限组合',
  'inputs': '实际源RowRun/FromRun、冻结复制Data/Copies和内部有限编码。',
  'risk': '不能把尚待证明的选择、Nested或规范性作为最终Expands前提。',
  'evidence': ['OneYOrdinaryForestTransport',
               'OneYOrdinaryValueTransport',
               'OneYOrdinaryPseudoTransport',
               'OneYOrdinaryCanonical'],
  'symbols': [],
  'declared_done': True,
  'delivered': True,
  'critical': True,
  'size': 'L',
  'optional': False},
 {'id': 'Z02',
  'title': 'DH/BM4仓库：KP强度源码审读',
  'group': '可选调查',
  'deps': ['V01'],
  'files': ['tracker/DHBMS-KP-REVIEW.md', 'tracker/dhbms-review-evidence.json'],
  'result': '固定e1849485提交，确认真实KP相关库的复用价值及外部ZFSet/Lθ语义边界；未冒充任意模型KP推导。',
  'inputs': '用户指定koteitan/dh-bms-wf-formal；只读克隆及第二agent独立复核。',
  'accept': ['定位KPModel、L powerset/range、ω1正则性/选择、宿主Nat/Ordinal及最终Reachable范围。', '本任务验收是源码强度审读；未全量编译或重新认证整库内核审计。'],
  'risk': '不能从相同Lean公理名单推断相同对象集合论强度；不由该库更改用户给出的Z₂上界/猜想区别。',
  'evidence': ['./DHBMS-KP-REVIEW.md', './dhbms-review-evidence.json'],
  'symbols': [],
  'declared_done': True,
  'delivered': False,
  'critical': False,
  'size': 'S',
  'optional': True}]

META = {'title': '1‑Y / KPω 形式化进度',
 'state': 'complete',
 'state_label': '证明完成 · 最终核验通过（2026-10-01）',
 'objective': '在 KPω + 存在不可数序数中，给出原 1-Y 算法的实际下降秩函数与完整 Hilbert 推导。',
 'scope': '秩函数覆盖所有合法表达式 E；字典序良序只针对 Desc(s) 与生成集 G。',
 'statement': 'KPω ⊢ ∀ν [UncountableOrdinal(ν) → ∃序数 χ≤ν, ∃集合函数 μ:E→χ, μ(∅)=0 ∧ ∀s≠∅ ∀N∈ω, μ(E_N(s))<μ(s)]。',
 'source_statement': '最终纯 ∈ 闭句为 KP1Y.OneYTheorem.mainSentence；KP1Y.OneYTheorem.theorem1_derivable : KP1Y.Derives '
                     'mainSentence。',
 'original_commit': '6533b2975f3cafb3582dc8f8127e9ea7144d7e69',
 'uncertainty': '无剩余数学或核验工作包；Z01（可选）未做。',
 'concurrency': '6个worker + 1个协调者（2026-10-01 Claude Code 会话）。文件按前缀独占；交接记录在 tracker/handoff/LANE-*.md。',
 'last_change': '第十九批 + 冷启动全量复核：567 模块 567 checked/0 cached PASS；4216 项声明审计仅 '
                'propext、Classical.choice、Quot.sound。theorem1_derivable 无前提。',
 'groups': ['既有成果', '反射支线', '有限组合', '结论支线', '主定理汇合', '最终验收', '可选调查'],
 'optional_edges': [],
 'boundary': '全部完成。见 tracker/FINAL-VERIFICATION.md、FINAL-STATEMENT-REVIEW.md。'}

WORK = {'Y04b': {'owner': 'LANE-A',
          'note': '独占 KP1Y/OneYCopySeams*.lean；随后 Y06 独占 '
                  'OneYCopyDescent*.lean。Y06坏根分支仅以Y05b边包含为命名接口hCanonical，待C交付后由协调者接上。'},
 'Y05b': {'owner': 'LANE-B / LANE-B2 / LANE-C / LANE-F(B助手) / LANE-D(C助手)',
          'note': 'B独占 OneYLowerCanon*/OneYLowerLayer*（逐层Lower规范性及四项输入下传）；C独占 '
                  'OneYTerminalBase*/OneYTerminalTower*/OneYTowerCanon*/OneYCanonicalExpansion*（Terminal层、k≥K塔、全塔汇合与A(E_N(s))⊆复制图）。已有OneYLower*/OneYTerminal*冻结只读。 '
                  'B2独占 OneYLowerBlock*/OneYLowerBottom*（Lower阻挡DecoratedBlockers、底行恢复/运输），B组装lower_layer_step_d。 '
                  'F(helper)独占 OneYLowerHelp*：lower_layer_pseudo_top_bound_d 与 lower_layer_extract_d（原伪父链/TopBound）。 '
                  'D(C助手)独占 OneYCanonHelper*：Terminal 底行四个出口 H1–H4。'},
 'Y08': {'owner': 'LANE-D',
         'note': '独占 '
                 'OneYRankStatement*（共享RankWitness谓词，先交付）、OneYInnerAbsoluteness*、OneYRankTransfer*（M03以M02精确命题为唯一前提）。'},
 'M05': {'owner': 'LANE-E',
         'note': '独占 '
                 'OneYTheorem*、OneYWellFounded*、OneYWellOrdering*、tracker/FINAL-STATEMENT-REVIEW.md；M04/M04b/M05及Q01草稿。'},
 'Y07a': {'owner': 'LANE-F', 'note': '独占 OneYExpansionOrder*、OneYSeeds*；首接缝值若需C的塔汇合则以单一命名引理为接口。'},
 'M02': {'owner': 'LANE-D',
         'note': '独占 OneYRankDescent*；先定义CopyDescentStatement（Y06目标形状，转交LANE-A），再证MinimumRankDescentStatement。'}}

WAVES = [{'id': 'P0',
  'title': '当前：预算、过滤、复制几何',
  'coordinator': '维护共享接口；开始准备提升保序。第三通道沿当前矩阵主线；局部已冻结接口可先消费。',
  'lanes': [['Y02c', 'Y02n', 'Y02p'], ['Y02j'], ['Y03h']],
  'gate': '预算出口一冻结就交给规范图，不等坏根；仅冻结变更批次做增量集成。'},
 {'id': 'P1',
  'title': '规范图与真实父算法',
  'coordinator': 'Y03f：消费稳定数值事实，交付同块后缀提升保序。',
  'coordinator_tasks': ['Y03f'],
  'lanes': [['M01a'], ['Y02k', 'Y02m'], ['Y03v', 'Y03j', 'Y03b', 'Y03k']],
  'gate': 'M01a 不依赖具体 A(s)；复制父算法与相对 S 是当前最长的结构证明链。'},
 {'id': 'P2a',
  'title': '复制根运输（当前）',
  'coordinator': 'Terminal由root，Lower与公共路径由ranked按文件独占并行；Terminal已交付。',
  'lanes': [['Y04x'], ['Y04z'], ['Y05p', 'Y05n']],
  'gate': '精确源根记录交付后即可接CopyNeeds及复制边分类。'},
 {'id': 'P2',
  'title': '实际μ、唯一复制定义、独立关系',
  'coordinator': '冻结唯一 CopyTower；后续反射拼接与重提取共同消费。',
  'lanes': [['M01', 'Y08a'], ['Y04a', 'Y04c'], ['Y07l']],
  'gate': '按实际前置错峰领取；μ不必等复制结束。'},
 {'id': 'P3',
  'title': '复制几何与数值展开',
  'coordinator': '检查同一份复制塔被两支实际使用。',
  'lanes': [['Y04d', 'Y04b'], ['Y05r', 'Y05c', 'Y07r'], ['Y05o']],
  'gate': '几何一交付即可接入规范重提取；无需等反射拼接完成。'},
 {'id': 'P4',
  'title': '规范重提取关口',
  'coordinator': '审核复制输入及重新提取证明未保留规范性假设。',
  'lanes': [['Y05b'], [], []],
  'gate': '这里的串行瓶颈无法仅靠增加并写同一文件的worker消除。'},
 {'id': 'P5',
  'title': '下降、次序事实、绝对性并行',
  'coordinator': '核对所有内部N、空/非空输出和复制差一。',
  'lanes': [['Y06', 'M02'], ['Y07a', 'Y07b'], ['Y08']],
  'gate': '实际秩下降和内外计算一致后才能回传μ。'},
 {'id': 'P6',
  'title': '把实际μ从L回传',
  'coordinator': '其余槽独立审阅接口、计算域与χ≤ν。',
  'lanes': [['M03'], [], []],
  'gate': '回传集合见证；不从L无降链直接推外部良基。'},
 {'id': 'P7',
  'title': '两类具体推论',
  'coordinator': '两支使用同一个真实μ和展开接口。',
  'lanes': [['M04'], ['M04b'], []],
  'gate': '通用定理的全部具体输入已解除。'},
 {'id': 'P8',
  'title': '闭句、忠实性与最终验收',
  'coordinator': 'Q02仅由root执行，维护根imports与Audit。',
  'lanes': [['M05', 'Q01', 'Q02'], [], []],
  'gate': '最终纯∈ Derives与命题忠实性、增量集成和公理审计全部通过才完工。'},
 {'id': 'OPT',
  'title': '可选调查（任意空余槽）',
  'coordinator': '不阻塞主线；只在空余槽启动。',
  'lanes': [['Z01'], [], []],
  'gate': '理论强度比较本身不构成可直接复用的对象推导。'}]

